name: video_trimmer
description: A Flutter package for trimming videos. This supports retrieving, trimming, and storage of trimmed video files to the file system.
version: 0.2.8
homepage: https://github.com/sbis04/video_trimmer

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # flutter_ffmpeg: ^0.4.2
  ffmpeg_kit_flutter_min_gpl: ^4.5.1-LTS
  video_player: ^2.2.7
  video_thumbnail: ^0.4.3
  path_provider: ^2.0.7
  intl: ^0.17.0
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
